services:
  app:
    build:
      context: ./main
      dockerfile: Dockerfile
      network: host
      args:
        - BUILDKIT_INLINE_CACHE=1
    ports:
      - "5001:5000"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - FLASK_ENV=production
      - OPENROUTER_API_KEY=your_api_key_here
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./data:/app/data